apiVersion: v1
kind: ResourceQuota
metadata:
  name: deny-high-priority
  namespace: team-b
spec:
  hard:
    pods: "0"
  scopeSelector:
    matchExpressions:
    - operator : In
      scopeName: PriorityClass
      values: ["high-priority"]

